spring:
  application:
    name: activity-service
  data:
    mongodb:
      database: fitnessActivity
      host: localhost
      port: 27017

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
